### ISSUE TITLE
Can't run go-thrust on debian 8 i386

### ISSUE THREAD

**Issue by l0oky** [miketheprogrammer/go-thrust#71]
I tried running my own projects, example projects, tutorials and everytime I get this error...
I am running i386 Debian 8, that's probably the issue here?
```bash
l0oky@laptop:~/Projects/go/src/github.com/miketheprogrammer/go-thrust/examples/jankybrowser$ go install
l0oky@laptop:~/Projects/go/src/github.com/miketheprogrammer/go-thrust/examples/jankybrowser$ jankybrowserGo-Thrust:2016/04/07 12:10:41 Thrust Client:: Initializing
Go-Thrust:2016/04/07 12:10:41 Attempting to start Thrust Core
Go-Thrust:2016/04/07 12:10:41 CMD:/home/l0oky/vendor/linux/x64/0.7.6/thrust_shell
Go-Thrust:2016/04/07 12:10:41 Thrust Core not started.
panic: Thrust Core not started.

goroutine 16 [running]:
runtime.panic(0x827d900, 0x1870e378)
	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xe9
log.(*Logger).Panic(0x1871a5d0, 0xb7415ec8, 0x1, 0x1)
	/usr/lib/go/src/pkg/log/log.go:193 +0x9f
github.com/miketheprogrammer/go-thrust/lib/spawn.Run()
	/home/l0oky/Projects/go/src/github.com/miketheprogrammer/go-thrust/lib/spawn/spawn_process.go:100 +0x572
github.com/miketheprogrammer/go-thrust/thrust.Start()
	/home/l0oky/Projects/go/src/github.com/miketheprogrammer/go-thrust/thrust/thrust.go:46 +0x21
main.main()
	/home/l0oky/Projects/go/src/github.com/miketheprogrammer/go-thrust/examples/jankybrowser/browser.go:35 +0x35

goroutine 19 [finalizer wait]:
runtime.park(0x8059db0, 0x84b65ac, 0x84b5129)
	/usr/lib/go/src/pkg/runtime/proc.c:1369 +0x94
runtime.parkunlock(0x84b65ac, 0x84b5129)
	/usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3f
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xc5
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x24
created by os/signal.init·1
	/usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x37

goroutine 17 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445
```

**Comment by miketheprogrammer** [comment]
It seems Thrust core will need to be updated to debian 8. I have no time to
do this currently. Maybe in the next 3 months. I'll put out a CTA for
someone to help

**Comment by miketheprogrammer** [comment]
It might be as easy as rebuilding it on Jessie, but that could take awhile.
